### ISSUE TITLE
Infografia Diego Ernesto Lopez Vasquez 1AS

### ISSUE THREAD

**Issue by DiegoLV117** [SistemasTecTlaxiaco/infografia-DiegoLV117#2]
[DIEGO.ERNESTO.LOPEZ.VAQUEZ.INFOGRAFIA.MAT.DISCRETAS.1.PARCIAL.pdf](https://github.com/SistemasTecTlaxiaco/infografia-DiegoLV117/files/12562265/DIEGO.ERNESTO.LOPEZ.VAQUEZ.INFOGRAFIA.MAT.DISCRETAS.1.PARCIAL.pdf)

**Comment by carla1131** [comment]
Redacion 10%
Exposición de ideas 15%
Organización de la información 15%
Imágenes 0%
Presentación visual  13%
Referencias 15%
Presentación 13%
calificación: 16.2/20
calificado por carla bautista

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
